<?php

/**
 * Returns the importmap for this application.
 *
 * - "path" is a path inside the asset mapper system. Use the
 *     "debug:asset-map" command to see the full list of paths.
 *
 * - "entrypoint" (JavaScript only) set to true for any module that will
 *     be used as an "entrypoint" (and passed to the importmap() Twig function).
 *
 * The "importmap:require" command can be used to add new entries to this file.
 *
 * This file has been auto-generated by the importmap commands.
 */
return [
    'app' => [
        'path' => './assets/app.js',
        'entrypoint' => true,
    ],
    'bootstrap/dist/css/bootstrap.min.css' => [
        'version' => '5.3.2',
        'type' => 'css',
    ],
    'admin-lte' => [
        'version' => '3.2.0',
    ],
    'jquery' => [
        'version' => '3.7.1',
    ],
    'chart.js' => [
        'version' => '4.4.1',
    ],
    '@kurkle/color' => [
        'version' => '0.3.2',
    ],
    'ionicons' => [
        'version' => '7.2.2',
    ],
    'bootstrap' => [
        'version' => '5.3.2',
    ],
    '@popperjs/core' => [
        'version' => '2.11.8',
    ],
    'admin-lte/dist/css/adminlte.min.css' => [
        'version' => '3.2.0',
        'type' => 'css',
    ],
    'ionicons/dist/collection/components/icon/icon.min.css' => [
        'version' => '7.2.2',
        'type' => 'css',
    ],
    'ionicons/dist/ionicons.js' => [
        'version' => '7.2.2',
    ],
];
