# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.


# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
  steamkey: C09B3CF321B2A0A529FF9EE34DC9F064
  user_class: AppBundle\Entity\User
services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    bind:
      $matchesDir: '%kernel.project_dir%/assets/matches/'
      $projectDir: '%kernel.project_dir%'
      $messengerAuditLogger: '@monolog.logger.messenger_audit'

  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'
      - '../src/Tests/'

  # controllers are imported separately to make sure services can be injected
  # as action arguments even if you don't extend any base controller class
  App\Controller\:
    resource: '../src/Controller/'
    tags: ['controller.service_arguments']

  # add more service definitions when explicit configuration is needed
  # please note that last definitions always *replace* previous ones

  GuzzleHttp\Client:
    class: GuzzleHttp\Client
    arguments:
      - { 'http_errors': false }
  Steam\Utility\GuzzleUrlBuilder:
    class: Steam\Utility\GuzzleUrlBuilder
  Steam\Runner\DecodeJsonStringRunner:
      class: Steam\Runner\DecodeJsonStringRunner
  Steam\Runner\GuzzleRunner:
    arguments:
      - '@GuzzleHttp\Client'
      - '@Steam\Utility\GuzzleUrlBuilder'

  Steam\Configuration:
    class: Steam\Configuration
    calls:
      - setSteamKey: ['%steamkey%']
  Steam\Steam:
    arguments:
      - '@Steam\Configuration'
    calls:
      - addRunner: ['@Steam\Runner\GuzzleRunner']
      - addRunner: ['@Steam\Runner\DecodeJsonStringRunner']


  #$steam->addRunner(new GuzzleRunner(new Client(), new GuzzleUrlBuilder()));
  #$steam->addRunner(new DecodeJsonStringRunner());
